main: ansneeze.ChronicleMines
version: 1.0.0
name: Chronicle Mines
author: ansneeze
api-version: 1.20

commands:
  chroniclemines:
    description: Comando principal del plugin Chronicle Mines (usa /chroniclemines o /crnmines)
    usage: /chroniclemines
    aliases: [crnmines]